@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 26 12:52:06 -0600 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim B400_state_machine_tb_behav -key {Behavioral:sim_1:Functional:B400_state_machine_tb} -tclbatch B400_state_machine_tb.tcl -view C:/Users/steph/OneDrive/Desktop/School/Microprocessor Architecture/viv.2018.2/viv.2018.2/B520_PVA_tb_behav.wcfg -log simulate.log"
call xsim  B400_state_machine_tb_behav -key {Behavioral:sim_1:Functional:B400_state_machine_tb} -tclbatch B400_state_machine_tb.tcl -view C:/Users/steph/OneDrive/Desktop/School/Microprocessor Architecture/viv.2018.2/viv.2018.2/B520_PVA_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
